### ISSUE TITLE
Add example OSS PWA's

### ISSUE THREAD

**Issue by PaulKinlan** [sylvhama/pwa-links#1]
Hi, this is a great resource. I was thinking it would be cool to list a number of different PWA's that showcase how you can build them with actual code.

Airhorner.com, developer.chrome.com/devsummit, proxx.app, squoosh.app are to name a few OSS ones that I've seen ;)

**Comment by sylvhama** [comment]
Great idea thanks! I've added a list: https://github.com/sylvhama/pwa-links/blob/master/README.md#open-source-projects
I like the fact it covers several types of apps: small productivity app, event website, online store, video game...
